#!/bin/bash

if [[ "$1$2" = *"--nocompile"* ]]
then
  echo "NoCompile"
  NoCompile=true
  Dir=""
else
  NoCompile=false
  Dir="build/"
fi

RepoPath="$( cd "$(dirname "$0")" ; pwd -P )"

HammingUser="hamming"

if [[ "$1$2" = *"--ff"* ]]
then
  firefoxProfile="$HOME/.firefox/${HammingUser}"
  rm -rf ${firefoxProfile}
  mkdir -p ${firefoxProfile}
  mkdir -p ${firefoxProfile}/chrome
  echo "@namespace url(\"http://www.mozilla.org/keymaster/gatekeeper/there.is.only.xul\");\n#TabsToolbar,#PersonalToolbar,#BookmarksToolbar,#MenuToolbar,#tabbrowser-tabs,#nav-bar,#TabsToolbar { display: none !important; }#main-window {max-width:1200px!important;min-width:1200px!important;min-height:676px!important;max-height:676px!important;}" \
      > ${firefoxProfile}/chrome/userChrome.css
  echo "user_pref(\"browser.feeds.showFirstRunUI\", false);"\
       "user_pref(\"devtools.toolbox.host\", \"window\");"\
       "user_pref(\"browser.tabs.warnOnClose\", false);" > ${firefoxProfile}/prefs.js
  firefox --profile ${firefoxProfile} --new-instance file://${RepoPath}/${Dir}index.html
else
  chromeRoot=$HOME/.chromeroot/
  chromeProfile="${chromeRoot}/${HammingUser}-profile"
  diskCacheDir="${chromeRoot}/${HammingUser}-profile-cache"
  diskCacheSize=4096
  mediaCacheSize=4096

  if $NoCompile; then
    rm -rf ${chromiumProfile}
  fi

  mkdir -p ${chromeRoot}
  chromium-browser \
        --remember-cert-error-decisions \
        --ignore-certificate-errors \
        --ignore-urlfetcher-cert-requests \
        --allow-running-insecure-content \
        --window-size=1200,675 \
        --window-position=0,0 \
        --no-pings \
        --user-data-dir=${chromeProfile} \
        --disk-cache-dir=${diskCacheDir} \
        --disk-cache-size=${diskCacheSize} \
        --media-cache-size=${mediaCacheSize} \
        --app=file://${RepoPath}/${Dir}index.html \
        2>&1
fi

