#!/bin/bash

if [ "$1" = "--fullscreen" ]
then
  size_command="--kiosk --start-fullscreen ${1}"
else
  size_command="--window-size=1200,675"
fi
index_path="$( cd "$(dirname "$0")" ; pwd -P )"
chromium-browser ${size_command} --app=file://${index_path}/index.html

